name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet build ./ClassToRecordAnalyzer.Analyzer/ClassToRecordAnalyzer.Analyzer.Package/ClassToRecordAnalyzer.Analyzer.Package.csproj -c Release -o nuget
    - name: Publish
      run: |
        cd nuget
        dotnet nuget push *.nupkg -k ${{ secrets.NUGET_KEY }}
